FROM node:18-alpine AS cs-nextjs-zustand-monorepo-test-runner
WORKDIR /app

ENV NODE_ENV test
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=cs-nextjs-zustand-monorepo-dev-builder /app/node_modules ./node_modules
COPY --from=cs-nextjs-zustand-monorepo-dev-builder /app/package.json ./package.json

RUN yarn

USER nextjs

CMD ["yarn", "next-webapp:test"]
